test asset upload/access
test download binary

add token

fix repo var

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,9 +1,9 @@
 name: Deploy Release
 
-on: [push]
-# on:
-#   release:
-#     types: [created]
+# on: [push]
+on:
+  release:
+    types: [created]
 
 jobs:
   build:
@@ -43,6 +43,20 @@ jobs:
     name: Deploy Binary
     runs-on: ubuntu-latest
     steps:
+      - name: Get Github Data
+        run: |
+          curl -o /dev/null -sH "${{ env.AUTH }}" ${{ env.GH_REPO }} || { echo "Error: Invalid repo, token or network issue!";  exit 1; }
+
+          response=$(curl -sH "${{ env.AUTH }}" ${{ env.GH_TAGS }})
+
+          eval $(echo "$response" | grep -C3 "name.:.\+$name" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
+          [ "$id" ] || { echo "Error: Failed to get asset id, response: $response" | awk 'length($0)<100' >&2; exit 1; }
+          GH_ASSET="${{ env.GH_REPO }}/releases/assets/$id"
+          echo "GH_ASSET=$GH_ASSET" >> $GITHUB_ENV
+        env:
+          GH_REPO: ${{ env.GITHUB_API_URL }}/repos/${{ env.GITHUB_REPOSITORY }}
+          GH_TAGS: ${{ env.GH_REPO }}/releases/tags/${{ env.GITHUB_REF_NAME }}
+          AUTH: "Authorization: token ${{ secrets.GH_TOKEN }}"
       - name: Create SSH key
         run: |
           mkdir -p ~/.ssh/
@@ -56,7 +70,14 @@ jobs:
           SSH_KEY_PATH: ${{ github.workspace }}/../private.key
       - name: Download Binary
         run: |
-          ssh -i $SSH_KEY_PATH github@159.65.35.29 'pwd'
+          echo "binary location"
+          echo ${{ env.GH_ASSET }}
+          # ssh -i $SSH_KEY_PATH github@159.65.35.29
+          # ssh -i $SSH_KEY_PATH github@159.65.35.29 "curl -vLJO -H 'Authorization: token $GITHUB_TOKEN' 'https://api.github.com/repos/victorhqc/victorhqc.com/releases/assets/:id'"
         shell: bash
         env:
+          GH_REPO: ${{ env.GITHUB_API_URL }}/repos/${{ env.GITHUB_REPOSITORY }}
+          GH_TAGS: ${{ env.GH_REPO }}/releases/tags/${{ env.GITHUB_REF_NAME }}
+          AUTH: "Authorization: token ${{ env.GITHUB_TOKEN }}"
           SSH_KEY_PATH: ${{ github.workspace }}/../private.key
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
